//! brush_lib.json registry: the truth source deciding which presets may
//! render through the tip-stamp engine.
//!
//! Generated by the upstream calibration pipeline (a probe pass plus a
//! per-preset truth gate); read here. A preset renders
//! through tips ONLY when `use_tips && gate.pass` - every other state
//! falls back to the legacy capsule path, which keeps band/v5 baselines
//! byte-identical by construction.
//!
//! Tolerant by design: unknown fields from the Python side land in
//! `extra` untouched, so the registry can evolve without breaking daub.

use anyhow::{Context, Result};
use serde::Deserialize;
use std::collections::HashMap;

#[derive(Clone, Debug, Deserialize)]
pub struct Gate {
    #[serde(rename = "pass")]
    pub pass: bool,
    /// Measurement payload written by tools/preset_gate.py; consumed by
    /// the gate tooling, not by the renderer.
    #[serde(default)]
    #[allow(dead_code)]
    pub measured: Option<serde_json::Value>,
}

#[derive(Clone, Debug, Deserialize)]
pub struct PresetEntry {
    /// Absolute path of the source .kpp file.
    pub kpp: String,
    #[serde(default)]
    #[allow(dead_code)] // registry truth + gate tooling input; routing uses tips_ok()
    pub supported: bool,
    #[serde(default)]
    pub use_tips: bool,
    #[serde(default)]
    pub unsupported_reason: Option<String>,
    /// Spacing as a fraction of dab diameter (linear model; "prior" until
    /// measured). When `auto_spacing_coeff` is set, Krita's automatic
    /// spacing applies instead: step = coeff * sqrt(diameter).
    #[serde(default = "default_spacing")]
    pub spacing: f64,
    /// Krita automatic spacing (preset `<Brush useAutoSpacing="1">`);
    /// overrides the linear model when present.
    #[serde(default)]
    #[allow(dead_code)] // registry truth; the engine takes the model via Tips::build
    pub auto_spacing_coeff: Option<f64>,
    #[serde(default)]
    pub spacing_source: String,
    #[serde(default)]
    pub gate: Option<Gate>,
    /// Measured anchors from the truth gate - cross-validation targets,
    /// never fit inputs. Written/read by tools/preset_gate.py.
    #[serde(default)]
    #[allow(dead_code)]
    pub width_profile: Option<Vec<f64>>,
    #[serde(default)]
    #[allow(dead_code)]
    pub alpha_profile: Option<Vec<f64>>,
    /// Everything else preset_pack.py records (probe facts, tip stats,
    /// option enable bits...) - kept so schema drift fails soft.
    #[serde(flatten)]
    pub extra: HashMap<String, serde_json::Value>,
}

fn default_spacing() -> f64 {
    0.25
}

impl PresetEntry {
    /// Routing predicate: all three conditions, or no tips.
    pub fn tips_ok(&self) -> bool {
        self.use_tips && self.gate.as_ref().is_some_and(|g| g.pass)
    }
}

#[derive(Clone, Debug, Deserialize)]
pub struct BrushLib {
    #[serde(default = "default_version")]
    #[allow(dead_code)] // schema self-description; shown by `daub presets`
    pub version: u32,
    /// Directory `kpp` paths are relative to when not absolute.
    pub tip_root: String,
    /// Layer names allowed on the tip path in Phase 1 (["X1"]).
    pub layers_tips: Vec<String>,
    /// Circuit breaker: estimated dabs above this degrade the tip layer
    /// back to capsule (sub-second guarantee, mechanised).
    pub max_dabs: u64,
    /// Keyed by Krita resource name - the exact string plan JSONs carry.
    #[serde(default)]
    pub presets: HashMap<String, PresetEntry>,
    /// Layer name -> tip engine, filled from layers_tips by load().
    #[serde(skip)]
    pub(crate) layer_set: std::collections::HashSet<String>,
}

fn default_version() -> u32 {
    1
}

impl BrushLib {
    /// Load the registry. Missing file is a hard error: unknown presets
    /// must fail loud, never silently fall back.
    pub fn load(path: &str) -> Result<BrushLib> {
        let raw = std::fs::read_to_string(path)
            .with_context(|| format!("reading brush registry {path}"))?;
        let mut lib: BrushLib = serde_json::from_str(&raw)
            .with_context(|| format!("parsing brush registry {path}"))?;
        lib.layer_set = lib.layers_tips.iter().cloned().collect();
        // kpp paths are written absolute by preset_pack.py, but resolve
        // relative ones against tip_root for hand-written registries.
        if !std::path::Path::new(&lib.tip_root).is_absolute() {
            if let Some(parent) = std::path::Path::new(path).parent() {
                let root = parent.join(&lib.tip_root);
                for e in lib.presets.values_mut() {
                    if !std::path::Path::new(&e.kpp).is_absolute() {
                        e.kpp = root.join(&e.kpp).to_string_lossy().into_owned();
                    }
                }
            }
        }
        Ok(lib)
    }

    /// Registry entry for a preset name; None = not registered (caller
    /// fails loud per plan - no silent capsule fallback).
    pub fn entry(&self, resource_name: &str) -> Option<&PresetEntry> {
        self.presets.get(resource_name)
    }

    /// May this LAYER render through tips at all?
    pub fn layer_tips(&self, layer: &str) -> bool {
        self.layer_set.contains(layer)
    }

    /// Dab circuit breaker budget.
    pub fn max_dabs(&self) -> u64 {
        self.max_dabs
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_lib() -> String {
        r#"{
  "version": 1,
  "tip_root": "brush_tips",
  "spacing_auto_prior": 0.25,
  "layers_tips": ["X1"],
  "max_dabs": 2500000,
  "presets": {
    "b) Basic-2 Opacity": {
      "kpp": "Krita_4_Default_Resources/b)_Basic-2_Opacity.kpp",
      "supported": true, "use_tips": true,
      "unsupported_reason": null,
      "spacing": 0.25, "spacing_source": "prior",
      "gate": {"pass": true, "measured": {"mean_abs": 22.1}},
      "tip_w": 200, "tip_h": 200,
      "probe_extra_future_field": {"anything": true}
    },
    "d) Ink-8 Sumi-e": {
      "kpp": "Krita_4_Default_Resources/d)_Ink-8_Sumi-e.kpp",
      "supported": false, "use_tips": false,
      "unsupported_reason": "paintopid=hairybrush",
      "spacing": 0.25, "spacing_source": "prior",
      "gate": {"pass": false, "measured": null}
    },
    "j) WaterC Something": {
      "kpp": "user/j)_WaterC_Something.kpp",
      "supported": true, "use_tips": true,
      "gate": {"pass": false, "measured": null}
    }
  }
}"#
        .to_string()
    }

    #[test]
    fn registry_schema_roundtrip_and_routing() {
        let dir = std::env::temp_dir().join(format!("daub_test_lib_{}", std::process::id()));
        std::fs::create_dir_all(dir.join("brush_tips")).unwrap();
        let path = dir.join("brush_lib.json");
        std::fs::write(&path, sample_lib()).unwrap();

        let lib = BrushLib::load(path.to_str().unwrap()).unwrap();
        assert_eq!(lib.max_dabs(), 2_500_000);
        assert!(lib.layer_tips("X1"));
        assert!(!lib.layer_tips("U3"));

        // relative kpp paths resolved against the registry's directory
        let b2 = lib.entry("b) Basic-2 Opacity").unwrap();
        assert!(std::path::Path::new(&b2.kpp).is_absolute());
        let expected = dir.join("brush_tips")
            .join("Krita_4_Default_Resources").join("b)_Basic-2_Opacity.kpp");
        assert_eq!(std::path::Path::new(&b2.kpp), expected);

        // routing predicate: three-way AND
        assert!(b2.tips_ok(), "supported+use_tips+gate.pass -> tips");
        let sumi = lib.entry("d) Ink-8 Sumi-e").unwrap();
        assert!(!sumi.tips_ok(), "unsupported stays capsule");
        let unmeasured = lib.entry("j) WaterC Something").unwrap();
        assert!(!unmeasured.tips_ok(), "gate not passed -> capsule");

        // unknown fields must not break the reader
        assert!(b2.extra.contains_key("probe_extra_future_field"));

        let _ = std::fs::remove_dir_all(dir);
    }

    #[test]
    fn registry_missing_file_fails_loud() {
        let err = BrushLib::load("Z:/definitely/not/here.json").unwrap_err();
        assert!(err.to_string().contains("reading brush registry"));
    }

    #[test]
    fn real_registry_legacy_keys() {
        let path = "tools/data/brush_lib.json";
        if !std::path::Path::new(path).is_file() {
            eprintln!("skip: brush_lib.json not present");
            return;
        }
        let lib = BrushLib::load(path).unwrap();
        // tips-eligible legacy: pure pressure-driven round tips.
        // gate.pass is RUNTIME STATE written back by preset_gate.py (the
        // per-preset truth gate) - a test must not pin it.
        for name in ["b) Basic-2 Opacity", "b) Basic-5 Size", "d) Ink-3 Gpen"] {
            let e = lib.entry(name).unwrap_or_else(|| panic!("{name} missing"));
            assert!(e.supported, "{name} must be supported");
            assert!(e.use_tips, "{name} must be tips-eligible");
        }
        // honestly excluded legacy (the old blind probe admitted these;
        // the order-agnostic scanner sees why they cannot be modelled):
        // Ink-1 soft edge + speed-driven size, Ink-2 composite sensors
        let ink1 = lib.entry("d) Ink-1 Precision").unwrap();
        assert!(!ink1.tips_ok(), "Ink-1 has SoftnessValue=0.1 + speed sensor");
        let ink2 = lib.entry("d) Ink-2 Fineliner").unwrap();
        assert!(!ink2.tips_ok(), "Ink-2 size is a sensorslist");
        // Sumi-e registered but excluded from tips (hairybrush)
        let sumi = lib.entry("d) Ink-8 Sumi-e").unwrap();
        assert!(!sumi.tips_ok());
    }

    /// Sentinel (09-09 tip-death incident): a bundle regeneration
    /// hardcoded layers_tips=["X1"] over the live ["X1","X1F","X1M"]
    /// and every ink line silently degraded to the capsule engine -
    /// plans still carried the X layer names, so nothing failed. The
    /// vendored registry is pinned at COMPILE TIME here; preset_pack.py
    /// carries live top-level fields (wash guard) as the source-side
    /// fix. If this fails, the wash happened again.
    #[test]
    fn vendored_registry_layers_tips_not_washed() {
        let raw = include_str!("../tools/data/brush_lib.json");
        let v: serde_json::Value = serde_json::from_str(raw).unwrap();
        let names: Vec<&str> = v["layers_tips"].as_array().expect("layers_tips")
            .iter().map(|x| x.as_str().unwrap()).collect();
        for layer in ["X1", "X1F", "X1M"] {
            assert!(names.contains(&layer),
                    "layers_tips washed: {names:?} lacks {layer}");
        }
    }

    /// Same sentinel against the upstream ORIGINAL registry
    /// (calibration-side copy; the two are byte-compared by
    /// tools/check_assets.py with only the kpp-path transform, so this
    /// is belt-and-braces on top of that). Runs only when
    /// $DAUB_KRMCP_TOOLS points at an upstream checkout.
    #[test]
    fn original_registry_layers_tips_not_washed() {
        let Some(dir) = std::env::var_os("DAUB_KRMCP_TOOLS") else {
            eprintln!("skip: DAUB_KRMCP_TOOLS not set");
            return;
        };
        let path = std::path::Path::new(&dir).join("brush_lib.json");
        if !path.is_file() {
            eprintln!("skip: brush_lib.json not present under DAUB_KRMCP_TOOLS");
            return;
        }
        let raw = std::fs::read_to_string(&path).unwrap();
        let v: serde_json::Value = serde_json::from_str(&raw).unwrap();
        let names: Vec<String> = v["layers_tips"].as_array()
            .expect("layers_tips")
            .iter().map(|x| x.as_str().unwrap().to_string()).collect();
        for layer in ["X1", "X1F", "X1M"] {
            assert!(names.iter().any(|n| n == layer),
                    "layers_tips washed: {names:?} lacks {layer}");
        }
    }
}
